version: '3'

services:
  web:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app/

    ports:
      - "8000:8000"

    env_file:
      - ./.env.dev

    depends_on:
      - db

  db:
    image: postgres:15.4-alpine

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_USER=django_db_user
      - POSTGRES_PASSWORD=django_db_password
      - POSTGRES_DB=django_dev

volumes:
  postgres_data: